server:
  image: liuhenghuo/ngrok
  ports:
    - "8082:80"
    - "4432:443"
    - "4443:4443"
  volumes:
    - /data/ngrok:/myfiles
  environment:
    - DOMAIN="ng.l0411.com"
  command: /bin/sh /server.sh
